### PR TITLE
Return file from cache if it already exists

### PR DESCRIPTION
**Pull request by donnapep**
* Refactor file controller to use the prototype pattern.
* `files` endpoint responds with file from disk if it exists.

### CODE REVIEW

**Comment by donnapep** [comment]
@stulees @rodrigopavezi Please review. Thx.

**Comment by donnapep** [comment]
@stulees @rodrigopavezi Also, any idea how this one can be validated?

**Comment by donnapep** [comment]
@stulees @rodrigopavezi Figured out the validation part. You should not see the timestamp of a previously downloaded file changing on subsequent requests for that same file. Also, in Terminal the "File Downloaded..." text shouldn't display if the file has already been downloaded.

**Comment by rodrigopavezi** [comment]
@donnapep looks good 👍 cheers

**Pull request merged**
