### PR TITLE
Log any uncaught exceptions

### PR DESCRIPTION
**Pull request by donnapep**
uncaught exception

### CODE REVIEW

**Comment by donnapep** [comment]
@stulees @rodrigopavezi Please review. Do you see a way to add a test? I would normally spy on `logger.error` but `logger` isn't a parameter that gets passed to `AppFactory`. It requires it directly. Thx.

**Comment by stulees** [comment]
@donnapep You could spy on `console.error`, ensure `debugging = true;` in your test, and validate `console.error` was called and if you what it was called with.

**Comment by donnapep** [comment]
@stulees I had to give up on adding a test for this. It was wreaking too much havoc and I couldn't figure out how to fix it.

However, in the process I did discover an issue where it was possible for the server to start up again before it had finished shutting down from a previous test. So I added optional callback parameters to the applicable functions, and use them in the tests to ensure shutdown is complete before attempting a restart.

Please review latest commits. Thx!

**Comment by stulees** [comment]
@donnapep 👍

**Pull request merged**
