### PR TITLE
Set up repo for development of Rise Cache

### PR DESCRIPTION
**Pull request by donnapep**
* Add base file structure and `package.json`.
* Add Gulpfile that has tasks for testing and linting.
* Include Babel so that code can be written in ES6.
* Add bare-bones `circle.yml`.

### CODE REVIEW

**Comment by donnapep** [comment]
@stulees @rodrigopavezi Please review. Let me know if I missed anything. Thx.

**Comment by stulees** [comment]
@donnapep Looks good to me 👍

**Comment by rodrigopavezi** [comment]
@donnapep looks good 👍 cheers

**Comment by tejohnso** [comment]
Hey guys why do we need babel in here?  Actually, I'm wondering about all nine of those `devDependencies`.

**Comment by rodrigopavezi** [comment]
@donnapep @stulees I think @tejohnso brought up a good point here. Node supports some ES6 so what if we try using it without babel and see how it goes? cheers

**Comment by donnapep** [comment]
@rodrigopavezi @tejohnso If we don't use Babel, then the tests won't pass. Mocha doesn't understand ES6.

**Comment by tejohnso** [comment]
@donnapep It should be ok.  Mocha runs inside the existing node environment and doesn't try to parse any test code.  We use mocha with es6 in a lot of projects.

**Pull request merged**
