### PR TITLE
Log error events as "error" and not "info"

### PR DESCRIPTION
**Pull request by donnapep**

### CODE REVIEW

**Comment by donnapep** [comment]
@stulees @rodrigopavezi Please review. Also, what's the criteria for deciding when we bump the version of RC now? Thx.

**Comment by stulees** [comment]
@donnapep 👍 re: bumping version, I would think we always semantic version bump but I'm not sure how it aligns with player installer. @rodrigopavezi ?

**Comment by rodrigopavezi** [comment]
@donnapep @stulees I would bump the version on every change so we don't loose track and end up forgetting to do so. Player uses the github commit hash so we are safe but bumping the version is a good practice. cheers

**Comment by donnapep** [comment]
@stulees @rodrigopavezi OK, the version has been bumped. Please let me know if this is good to go now. Thx.

**Comment by stulees** [comment]
@donnapep 👍

**Pull request merged**
