### PR TITLE
Use single data model class

### PR DESCRIPTION
**Pull request by donnapep**

### CODE REVIEW

**Comment by donnapep** [comment]
@stulees @rodrigopavezi Please review. Thx.

**Comment by donnapep** [comment]
@rodrigopavezi Yeah, good point. Also, I'd like to introduce folders that map to our source folders. It's a bit hard to understand which files test what right now.

**Comment by rodrigopavezi** [comment]
@donnapep agreed about the folder. cheers

**Comment by donnapep** [comment]
@stulees @rodrigopavezi Please review latest commits. Thx.

**Comment by stulees** [comment]
@donnapep Can you rebase, cheers

**Comment by donnapep** [comment]
@stulees Done.

**Comment by donnapep** [comment]
@stulees Will fix the failure tomorrow.

**Comment by donnapep** [comment]
@stulees @rodrigopavezi Please review. Thx.

**Pull request merged**
