### PR TITLE
Gracefully handling potential startup errors

### PR DESCRIPTION
**Pull request by stulees**
- Check if RiseDisplayNetworkII.ini file exists and if it doesn't then store as `null` value and warn in the console
- Check if the cache directory exists and if so run the cleanup job

### CODE REVIEW

**Comment by stulees** [comment]
@donnapep @rodrigopavezi Please review, thanks

**Comment by rodrigopavezi** [comment]
@stulees curious, what about tests?

**Comment by stulees** [comment]
@rodrigopavezi We have unit tests for the `fileExists` function, so I didn't see much more value in additional tests. I also wasn't sure how to go about writing tests towards the app itself as we currently don't have any. Do you have an idea as to how to do that?

**Comment by rodrigopavezi** [comment]
@stulees I would write something on the ping test for instance that checks what happens when not mocking the `config.riseDisplayNetworkIIPath` here https://github.com/Rise-Vision/rise-cache-v2/blob/master/test/integration/ping-test.js#L21. We could check whether the server still up or the console message. 

For the others I would write unit tests on the file download and metadata tests to see that display id is not on the request and also proxy is not used when again not mocking the `config.riseDisplayNetworkIIPath`. 

What do you think? 

cheers

**Comment by stulees** [comment]
@rodrigopavezi Okay I'll have a go at those, thanks.

**Comment by stulees** [comment]
@rodrigopavezi Please review last commit. I couldn't see a way to detect the exact request options to determine what value `proxy` is set with, but I think these tests suffice. Thanks

**Comment by rodrigopavezi** [comment]
@stulees awesome 👍  cheers

**Pull request merged**
