### PR TITLE
Download file and save to disk

### PR DESCRIPTION
**Pull request by donnapep**
* Create download folder if it does not exist.
* Add route for download ing file and saving to download folder with encrypted file name.
* Create middleware for logging errors.

### CODE REVIEW

**Comment by donnapep** [comment]
@rodrigopavezi Any thoughts on how to test streaming the file to disk?

**Comment by donnapep** [comment]
@rodrigopavezi Can you review what I have so far and if OK I'll merge and refactor?

**Comment by donnapep** [comment]
Sorry @stulees. You too, please review.

**Comment by donnapep** [comment]
@rodrigopavezi Or maybe it would be better to close this one now and start fresh with the dependency injection approach to avoid merge conflicts. What do you think?

**Comment by stulees** [comment]
@donnapep 👍

**Comment by rodrigopavezi** [comment]
@donnapep I think it is good to close this as we would have to fix the merging issues. cheers

**Pull request closed without merging**
