### PR TITLE
Add proxy support

### PR DESCRIPTION
**Pull request by donnapep**
* Integrate `node-http-proxy` library that handles returning file to client.

### CODE REVIEW

**Comment by donnapep** [comment]
@stulees @rodrigopavezi Please review. Thx.

**Comment by stulees** [comment]
@donnapep Looks good  👍 but defer to @rodrigopavezi also

**Comment by rodrigopavezi** [comment]
@donnapep code looks good, but it still not working for this url http://localhost:9494/files?url=https://upload.wikimedia.org/wikipedia/commons/3/36/Hopetoun_falls.jpg. I reckon there is something else to be done with proxy web options. For instance, https://github.com/Rob--W/cors-anywhere/blob/master/lib/cors-anywhere.js#L84 here it sets the header host. cheers

**Comment by rodrigopavezi** [comment]
@donnapep Just to help you with that. I debugged our https://github.com/Rise-Vision/proxy-server when calling web for that url. it calls it with the following

**option**
```
{ changeOrigin: false,
  prependPath: false,
  target: 
   Url {
     protocol: 'https:',
     slashes: true,
     auth: null,
     host: 'upload.wikimedia.org',
     port: null,
     hostname: 'upload.wikimedia.org',
     hash: null,
     search: null,
     query: null,
     pathname: '/wikipedia/commons/3/36/Hopetoun_falls.jpg',
     path: '/wikipedia/commons/3/36/Hopetoun_falls.jpg',
     href: 'https://upload.wikimedia.org/wikipedia/commons/3/36/Hopetoun_falls.jpg' },
  headers: { host: 'upload.wikimedia.org' } }
```

*req.url**
```
/wikipedia/commons/3/36/Hopetoun_falls.jpg
```

I see they also do something different on this lines https://github.com/Rob--W/cors-anywhere/blob/master/lib/cors-anywhere.js#L88-L95
I am not sure we have to do something similar to support others urls

I hope that helps.

Cheers

**Comment by donnapep** [comment]
@rodrigopavezi Thanks! In this code snippet:

    target: 
       Url {

what is `Url`?

**Comment by rodrigopavezi** [comment]
@donnapep I think it is an object created by [url.parse](https://nodejs.org/docs/latest/api/url.html#url_url_parse_urlstring_parsequerystring_slashesdenotehost). 

cors lib runs it here: https://github.com/Rob--W/cors-anywhere/blob/master/lib/cors-anywhere.js#L206

cheers

**Comment by donnapep** [comment]
@rodrigopavezi Setting the host header fixed it. I could see us having to tweak these options as different scenarios pop up. Please review. Thx.

**Comment by rodrigopavezi** [comment]
@donnapep I am not sure why by this following url stopped from being downloaded. It wasn't streaming before and changing to use the was supposed to fix that. 

http://localhost:9494/files/?url=https://storage.googleapis.com/risemedialibrary-f114ad26-949d-44b4-87e9-8528afc76ce4/general_die_splitting_and_cleaning_instructions.mp4

Do you know what could be happening?

cheers

**Comment by rodrigopavezi** [comment]
@donnapep I think the issues is related to the headers. I can see in the browser that the response headers are not the same as the one from the original server. cheers

**Comment by donnapep** [comment]
@rodrigopavezi I can see that 2 requests are being made back-to-back. The first request starts the file downloading and then the subsequent request is trying to read it from the cache. Do you know why it would make 2 requests? Do you think [this card](https://goo.gl/uthFLi) might fix it?

**Comment by donnapep** [comment]
@rodrigopavezi I'd like to address this on a separate PR / card. We really need to get this change merged so we can branch off of it for subsequent changes. What do you think?

**Comment by rodrigopavezi** [comment]
@donnapep for playing the video the browser player needs to make 3 requests for this file. I assume it does that because there are informations on different parts of the video file. One of the requests asks for a range of bytes from the end of the file than returns to ask for range of bytes from the beginning of the file. I have explained the case in details on this card [save-file-headers](https://trello.com/c/3bNd3DW2/1898-3-rc-save-file-headers).

I think the work on the card you mentioned will fix the stream but will not resolve the download issue. 

Sure, makes sense to merge this PR and target these issues on another card.

👍 

Cheers

**Pull request merged**
